apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 3 * * *"
  startingDeadlineSeconds: 900
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    ttlSecondsAfterFinished: 86400
    backoffLimit: 0
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: clearsessions
              image: django_app:latest
              imagePullPolicy: IfNotPresent
              workingDir: /webapp/src
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - secretRef:
                    name: django-env
              env:
                - name: DEBUG
                  value: "False"
