apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
        app.kubernetes.io/name: django
    spec:
      containers:
        - name: django
          image: django_app:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-env
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-env
                  key: DATABASE_URL
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "127.0.0.1,localhost"
