apiVersion: v1
kind: Pod
metadata:
  name: django
  labels:
    app: django
spec:
  containers:
    - name: django
      image: django_app:latest
      imagePullPolicy: Never
      ports:
        - name: http
          containerPort: 80
      env:
        - name: SECRET_KEY
          value: dev
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "127.0.0.1,localhost"
        - name: DATABASE_URL
          value: "postgres://test_k8s:OwOtBep9Frut@192.168.100.111:55432/test_k8s"